export const REGION_DISPLAY_NAMES = {
  indonesiacentral: "Indonesia Central",
  uaenorth: "UAE North",
  switzerlandnorth: "Switzerland North",
  israelcentral: "Israel Central",
  francecentral: "France Central",
  chilecentral: "Chile Central",
  germanywestcentral: "Germany West Central",
  mexicocentral: "Mexico Central",
  eastasia: "East Asia",
  southeastasia: "Southeast Asia",
  brazilsouth: "Brazil South",
  uswest: "US West",
  canadacentral: "Canada Central",
  westus: "West US",
  centralus: "Central US",
  northeurope: "North Europe",
  italynorth: "Italy North",
  swedencentral: "Sweden Central",
  westindia: "West India",
  southcentralus: "South Central US",
};
